--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI_Drivers_Client_BLE;

package body PolyORB_HI_Generated.Subprograms is

  procedure Client_BLE_Receive
   renames PolyORB_HI_Drivers_Client_BLE.Receive;

end PolyORB_HI_Generated.Subprograms;
