--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package body PolyORB_HI_Generated.Types is

  ------------
  -- Length -- 
  ------------

  function Length
   (A : T_Uint16_Buffer_Max_impl)
   return Standard.Integer
  is
  begin
    return A'Length;
  end Length;

end PolyORB_HI_Generated.Types;
