--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI.Utils;
with DeviceConfig_node1_crazyflie_ble_pohiada;
with PolyORB_HI_Generated.Deployment;
with DeviceConfig_node2_client_ble_pohiada;
with System;

package PolyORB_HI_Generated.Naming is

  --  Naming Table for bus bluetooth_crazyflie_cv

  process_package_bluetooth_crazyflie_cv_Naming_Table : constant PolyORB_HI.Utils.Naming_Table_Type :=
   (PolyORB_HI_Generated.Deployment.crazyflie_v2_partition_K =>
     (PolyORB_HI.Utils.To_Hi_String
       ("{channel 80}"),
      0,
      DeviceConfig_node1_crazyflie_ble_pohiada.pohidrv_node1_crazyflie_ble_pohiada_cv'Address),
    PolyORB_HI_Generated.Deployment.x86_partition_K =>
     (PolyORB_HI.Utils.To_Hi_String
       ("{channel 80}"),
      0,
      DeviceConfig_node2_client_ble_pohiada.pohidrv_node2_client_ble_pohiada_cv'Address),
    others =>
     (PolyORB_HI.Utils.To_Hi_String
       (""),
      0,
      System.null_Address));

end PolyORB_HI_Generated.Naming;
