--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI.Port_Kinds;
with System;
with PolyORB_HI_Generated.Marshallers;
with PolyORB_HI_Generated.Transport;
with PolyORB_HI.Thread_Interrogators;
pragma Elaborate_All (PolyORB_HI.Thread_Interrogators);
with ground_wrappers;
with PolyORB_HI_Generated.Subprograms;

package body PolyORB_HI_Generated.Activity is

  --  BEGIN: Data types used by all instances of component 
  --  ground_ground.others

  type ground_CV_Thread_ground_ground_others_Integer_Array is
   array (ground_CV_Thread_ground_ground_others_Port_Type)
     of Standard.Integer;

  type ground_CV_Thread_ground_ground_others_Port_Kind_Array is
   array (ground_CV_Thread_ground_ground_others_Port_Type)
     of PolyORB_HI.Port_Kinds.Port_Kind;

  subtype UT_Activity_X86_Partition_1_Max_Port_Image_Size is
   Integer range 1 .. PolyORB_HI_Generated.Deployment.Max_Port_Image_Size;

  subtype UT_Activity_X86_Partition_ground_CV_Thread_ground_ground_others_Port_Image_Array_Component is
   Standard.String
     (UT_Activity_X86_Partition_1_Max_Port_Image_Size);

  type ground_CV_Thread_ground_ground_others_Port_Image_Array is
   array (ground_CV_Thread_ground_ground_others_Port_Type)
     of UT_Activity_X86_Partition_ground_CV_Thread_ground_ground_others_Port_Image_Array_Component;

  type ground_CV_Thread_ground_ground_others_Address_Array is
   array (ground_CV_Thread_ground_ground_others_Port_Type)
     of System.Address;

  type ground_CV_Thread_ground_ground_others_Overflow_Protocol_Array is
   array (ground_CV_Thread_ground_ground_others_Port_Type)
     of PolyORB_HI.Port_Kinds.Overflow_Handling_Protocol;

  --  END: Data types used by all instances of component ground_ground.others

  process_package_ground_Port_Kinds : constant ground_CV_Thread_ground_ground_others_Port_Kind_Array :=
   (OUTPORT_start_demo =>
     PolyORB_HI.Port_Kinds.Out_Event_Data_Port);

  process_package_ground_Port_Images : constant ground_CV_Thread_ground_ground_others_Port_Image_Array :=
   (OUTPORT_start_demo =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.x86_partition_ground_OUTPORT_start_demo_K));

  process_package_ground_FIFO_Sizes : constant ground_CV_Thread_ground_ground_others_Integer_Array :=
   (OUTPORT_start_demo =>
     -1);

  process_package_ground_Offsets : constant ground_CV_Thread_ground_ground_others_Integer_Array :=
   (OUTPORT_start_demo =>
     0);

  process_package_ground_Overflow_Protocols : constant ground_CV_Thread_ground_ground_others_Overflow_Protocol_Array :=
   (OUTPORT_start_demo =>
     PolyORB_HI.Port_Kinds.Dropoldest);

  process_package_ground_Urgencies : constant ground_CV_Thread_ground_ground_others_Integer_Array :=
   (OUTPORT_start_demo =>
     0);

  process_package_ground_Total_FIFO_Size : constant Standard.Integer :=
   0;

  type UT_Activity_X86_Partition_ground_OUTPORT_start_demo_Destinations_Array is
   array (Standard.Positive range <>)
     of PolyORB_HI_Generated.Deployment.Port_Type;

  ground_OUTPORT_start_demo_Destinations : constant UT_Activity_X86_Partition_ground_OUTPORT_start_demo_Destinations_Array :=
   UT_Activity_X86_Partition_ground_OUTPORT_start_demo_Destinations_Array'
     (1 =>
       PolyORB_HI_Generated.Deployment.crazyflie_v2_partition_vt_crazyflie_start_demo_INPORT_artificial_start_demo_K);

  process_package_ground_N_Destinations : constant ground_CV_Thread_ground_ground_others_Integer_Array :=
   (OUTPORT_start_demo =>
     1);

  ground_Destinations : constant ground_CV_Thread_ground_ground_others_Address_Array :=
   (OUTPORT_start_demo =>
     ground_OUTPORT_start_demo_Destinations'Address);

  package process_package_ground_Interrogators is
   new PolyORB_HI.Thread_Interrogators
     (Port_Type => ground_CV_Thread_ground_ground_others_Port_Type,
      Integer_Array => ground_CV_Thread_ground_ground_others_Integer_Array,
      Port_Kind_Array => ground_CV_Thread_ground_ground_others_Port_Kind_Array,
      Port_Image_Array => ground_CV_Thread_ground_ground_others_Port_Image_Array,
      Address_Array => ground_CV_Thread_ground_ground_others_Address_Array,
      Overflow_Protocol_Array => ground_CV_Thread_ground_ground_others_Overflow_Protocol_Array,
      Thread_Interface_Type => ground_CV_Thread_ground_ground_others_Interface,
      Current_Entity => PolyORB_HI_Generated.Deployment.x86_partition_ground_K,
      Thread_Port_Kinds => process_package_ground_Port_Kinds,
      Has_Event_Ports => True,
      Thread_Port_Images => process_package_ground_Port_Images,
      Thread_Fifo_Sizes => process_package_ground_FIFO_Sizes,
      Thread_Fifo_Offsets => process_package_ground_Offsets,
      Thread_Overflow_Protocols => process_package_ground_Overflow_Protocols,
      Urgencies => process_package_ground_Urgencies,
      Global_Data_Queue_Size => process_package_ground_Total_FIFO_Size,
      N_Destinations => process_package_ground_N_Destinations,
      Destinations => ground_Destinations,
      Marshall => PolyORB_HI_Generated.Marshallers.Marshall,
      Send => PolyORB_HI_Generated.Transport.Send,
      Next_Deadline => process_package_ground_Task.Next_Deadline);

  --  Periodic task : ground

  -----------------
  -- Send_Output -- 
  -----------------

  function Send_Output
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : ground_CV_Thread_ground_ground_others_Port_Type)
   return PolyORB_HI.Errors.Error_Kind
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    return process_package_ground_Interrogators.Send_Output
     (Port);
  end Send_Output;

  ---------------
  -- Put_Value -- 
  ---------------

  procedure Put_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : ground_CV_Thread_ground_ground_others_Interface)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    process_package_ground_Interrogators.Put_Value
     (Thread_Interface);
  end Put_Value;

  --------------------------------
  -- process_package_ground_Job -- 
  --------------------------------

  procedure process_package_ground_Job
   (Result : out PolyORB_HI.Errors.Error_Kind)
  is
    Error_Ü : PolyORB_HI.Errors.Error_Kind;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Call the thread compute entrypoint
    ground_wrappers.gui_polling_ground
     (PolyORB_HI_Generated.Deployment.x86_partition_ground_K);
    --  Set the OUT port values
    --  Send the OUT ports
    Error_Ü :=
     process_package_ground_Interrogators.Send_Output
       (OUTPORT_start_demo);
    --  Return error code
    Result :=
     Error_Ü;
  end process_package_ground_Job;

  -----------------------------
  -- Client_BLE_receiver_Job -- 
  -----------------------------

  procedure Client_BLE_receiver_Job
   (Result : out PolyORB_HI.Errors.Error_Kind)
  is
    Error_Ü : constant PolyORB_HI.Errors.Error_Kind :=
     PolyORB_HI.Errors.Error_None;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Call implementation
    PolyORB_HI_Generated.Subprograms.Client_BLE_Receive;
    --  Return error code
    Result :=
     Error_Ü;
  end Client_BLE_receiver_Job;

end PolyORB_HI_Generated.Activity;
