--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI.Errors;
with PolyORB_HI_Generated.Deployment;
with Ada.Real_Time;
with PolyORB_HI.Periodic_Task;
pragma Elaborate_All (PolyORB_HI.Periodic_Task);
with PolyORB_HI_Generated.Types;
with PolyORB_HI.Sporadic_Task;
pragma Elaborate_All (PolyORB_HI.Sporadic_Task);
with PolyORB_HI.Background_Task;
pragma Elaborate_All (PolyORB_HI.Background_Task);

package PolyORB_HI_Generated.Activity is

  --  Periodic task : vt_crazyflie_pulse

  procedure process_package_vt_crazyflie_pulse_Job
   (Result : out PolyORB_HI.Errors.Error_Kind);

  package process_package_vt_crazyflie_pulse_Task is
   new PolyORB_HI.Periodic_Task
     (Entity => PolyORB_HI_Generated.Deployment.crazyflie_v2_partition_vt_crazyflie_pulse_K,
      Task_Period => Ada.Real_Time.Milliseconds
       (2000),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (2000),
      Dispatch_Offset => Ada.Real_Time.Milliseconds
       (0),
      Task_Priority => 1,
      Task_Stack_Size => 5000,
      Job => process_package_vt_crazyflie_pulse_Job);

  --  BEGIN: Entities used by all instances of component 
  --  vt_crazyflie_start_demo_vt_crazyflie_start_demo.others

  type vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type is
   (INPORT_artificial_start_demo);

  type vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Interface 
   (Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type := vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type'First)
  is
    record
      case Port is
        when INPORT_artificial_start_demo =>
          INPORT_artificial_start_demo_DATA : PolyORB_HI_Generated.Types.T_Uint16_Buffer_impl;
        pragma Warnings (Off);
        when others =>
          null;
        pragma Warnings (On);
      end case;
    end record;

  procedure Receive_Input
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type);

  function Get_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
   return vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Interface;

  function Get_Sender
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
   return PolyORB_HI_Generated.Deployment.Entity_Type;

  function Get_Count
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
   return Standard.Integer;

  function Get_Time_Stamp
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
   return Ada.Real_Time.Time;

  procedure Next_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type);

  procedure Store_Received_Message
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Interface;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Time_Stamp : Ada.Real_Time.Time :=
      Ada.Real_Time.Clock);

  procedure Wait_For_Incoming_Events
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : out vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type);

  --  END: Entities used by all instances of component 
  --  vt_crazyflie_start_demo_vt_crazyflie_start_demo.others

  --  Sporadic task : vt_crazyflie_start_demo

  procedure process_package_vt_crazyflie_start_demo_Job
   (Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type;
    Result : out PolyORB_HI.Errors.Error_Kind);

  package process_package_vt_crazyflie_start_demo_Task is
   new PolyORB_HI.Sporadic_Task
     (Port_Type => vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type,
      Entity => PolyORB_HI_Generated.Deployment.crazyflie_v2_partition_vt_crazyflie_start_demo_K,
      Task_Period => Ada.Real_Time.Milliseconds
       (1),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (1),
      Task_Priority => 10,
      Task_Stack_Size => 5000,
      Job => process_package_vt_crazyflie_start_demo_Job,
      Wait_For_Incoming_Events => Wait_For_Incoming_Events);

  --  Background task : receiver

  procedure Crazyflie_BLE_receiver_Job
   (Result : out PolyORB_HI.Errors.Error_Kind);

  package Crazyflie_BLE_receiver_Task is
   new PolyORB_HI.Background_Task
     (Entity => PolyORB_HI_Generated.Deployment.driver_Crazyflie_BLE_receiver_K,
      Task_Priority => 10,
      Task_Stack_Size => 10000,
      Job => Crazyflie_BLE_receiver_Job);

end PolyORB_HI_Generated.Activity;
