--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with vt_crazyflie_pulse_wrappers;
with PolyORB_HI.Port_Kinds;
with System;
with PolyORB_HI_Generated.Marshallers;
with PolyORB_HI_Generated.Transport;
with PolyORB_HI.Thread_Interrogators;
pragma Elaborate_All (PolyORB_HI.Thread_Interrogators);
with vt_crazyflie_start_demo_wrappers;
with PolyORB_HI_Generated.Subprograms;

package body PolyORB_HI_Generated.Activity is

  --  Periodic task : vt_crazyflie_pulse

  --  BEGIN: Data types used by all instances of component 
  --  vt_crazyflie_start_demo_vt_crazyflie_start_demo.others

  type vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Integer_Array is
   array (vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
     of Standard.Integer;

  type vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Kind_Array is
   array (vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
     of PolyORB_HI.Port_Kinds.Port_Kind;

  subtype UT_Activity_Crazyflie_V2_Partition_1_Max_Port_Image_Size is
   Integer range 1 .. PolyORB_HI_Generated.Deployment.Max_Port_Image_Size;

  subtype UT_Activity_Crazyflie_V2_Partition_vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Image_Array_Component is
   Standard.String
     (UT_Activity_Crazyflie_V2_Partition_1_Max_Port_Image_Size);

  type vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Image_Array is
   array (vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
     of UT_Activity_Crazyflie_V2_Partition_vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Image_Array_Component;

  type vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Address_Array is
   array (vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
     of System.Address;

  type vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Overflow_Protocol_Array is
   array (vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
     of PolyORB_HI.Port_Kinds.Overflow_Handling_Protocol;

  --  END: Data types used by all instances of component 
  --  vt_crazyflie_start_demo_vt_crazyflie_start_demo.others

  process_package_vt_crazyflie_start_demo_Port_Kinds : constant vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Kind_Array :=
   (INPORT_artificial_start_demo =>
     PolyORB_HI.Port_Kinds.In_Event_Data_Port);

  process_package_vt_crazyflie_start_demo_Port_Images : constant vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Image_Array :=
   (INPORT_artificial_start_demo =>
     PolyORB_HI_Generated.Deployment.Port_Image
       (PolyORB_HI_Generated.Deployment.crazyflie_v2_partition_vt_crazyflie_start_demo_INPORT_artificial_start_demo_K));

  process_package_vt_crazyflie_start_demo_FIFO_Sizes : constant vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Integer_Array :=
   (INPORT_artificial_start_demo =>
     1);

  process_package_vt_crazyflie_start_demo_Offsets : constant vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Integer_Array :=
   (INPORT_artificial_start_demo =>
     1);

  process_package_vt_crazyflie_start_demo_Overflow_Protocols : constant vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Overflow_Protocol_Array :=
   (INPORT_artificial_start_demo =>
     PolyORB_HI.Port_Kinds.Dropoldest);

  process_package_vt_crazyflie_start_demo_Urgencies : constant vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Integer_Array :=
   (INPORT_artificial_start_demo =>
     0);

  process_package_vt_crazyflie_start_demo_Total_FIFO_Size : constant Standard.Integer :=
   1;

  process_package_vt_crazyflie_start_demo_N_Destinations : constant vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Integer_Array :=
   (INPORT_artificial_start_demo =>
     0);

  vt_crazyflie_start_demo_Destinations : constant vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Address_Array :=
   (INPORT_artificial_start_demo =>
     System.null_Address);

  package process_package_vt_crazyflie_start_demo_Interrogators is
   new PolyORB_HI.Thread_Interrogators
     (Port_Type => vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type,
      Integer_Array => vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Integer_Array,
      Port_Kind_Array => vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Kind_Array,
      Port_Image_Array => vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Image_Array,
      Address_Array => vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Address_Array,
      Overflow_Protocol_Array => vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Overflow_Protocol_Array,
      Thread_Interface_Type => vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Interface,
      Current_Entity => PolyORB_HI_Generated.Deployment.crazyflie_v2_partition_vt_crazyflie_start_demo_K,
      Thread_Port_Kinds => process_package_vt_crazyflie_start_demo_Port_Kinds,
      Has_Event_Ports => True,
      Thread_Port_Images => process_package_vt_crazyflie_start_demo_Port_Images,
      Thread_Fifo_Sizes => process_package_vt_crazyflie_start_demo_FIFO_Sizes,
      Thread_Fifo_Offsets => process_package_vt_crazyflie_start_demo_Offsets,
      Thread_Overflow_Protocols => process_package_vt_crazyflie_start_demo_Overflow_Protocols,
      Urgencies => process_package_vt_crazyflie_start_demo_Urgencies,
      Global_Data_Queue_Size => process_package_vt_crazyflie_start_demo_Total_FIFO_Size,
      N_Destinations => process_package_vt_crazyflie_start_demo_N_Destinations,
      Destinations => vt_crazyflie_start_demo_Destinations,
      Marshall => PolyORB_HI_Generated.Marshallers.Marshall,
      Send => PolyORB_HI_Generated.Transport.Send,
      Next_Deadline => process_package_vt_crazyflie_start_demo_Task.Next_Deadline);

  --  Sporadic task : vt_crazyflie_start_demo

  --------------------------------------------
  -- process_package_vt_crazyflie_pulse_Job -- 
  --------------------------------------------

  procedure process_package_vt_crazyflie_pulse_Job
   (Result : out PolyORB_HI.Errors.Error_Kind)
  is
    Error_Ü : constant PolyORB_HI.Errors.Error_Kind :=
     PolyORB_HI.Errors.Error_None;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Call the thread compute entrypoint
    vt_crazyflie_pulse_wrappers.artificial_pulse
     (PolyORB_HI_Generated.Deployment.crazyflie_v2_partition_vt_crazyflie_pulse_K);
    --  Return error code
    Result :=
     Error_Ü;
  end process_package_vt_crazyflie_pulse_Job;

  -------------------
  -- Receive_Input -- 
  -------------------

  procedure Receive_Input
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    process_package_vt_crazyflie_start_demo_Interrogators.Receive_Input
     (Port);
  end Receive_Input;

  ---------------
  -- Get_Value -- 
  ---------------

  function Get_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
   return vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Interface
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return process_package_vt_crazyflie_start_demo_Interrogators.Get_Value
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Value;

  ----------------
  -- Get_Sender -- 
  ----------------

  function Get_Sender
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
   return PolyORB_HI_Generated.Deployment.Entity_Type
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return process_package_vt_crazyflie_start_demo_Interrogators.Get_Sender
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Sender;

  ---------------
  -- Get_Count -- 
  ---------------

  function Get_Count
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
   return Standard.Integer
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return process_package_vt_crazyflie_start_demo_Interrogators.Get_Count
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Count;

  --------------------
  -- Get_Time_Stamp -- 
  --------------------

  function Get_Time_Stamp
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
   return Ada.Real_Time.Time
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    pragma Warnings
     (Off,
      "*return*");
    return process_package_vt_crazyflie_start_demo_Interrogators.Get_Time_Stamp
     (Port);
    pragma Warnings
     (On,
      "*return*");
  end Get_Time_Stamp;

  ----------------
  -- Next_Value -- 
  ----------------

  procedure Next_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    process_package_vt_crazyflie_start_demo_Interrogators.Next_Value
     (Port);
  end Next_Value;

  ------------------------------
  -- Wait_For_Incoming_Events -- 
  ------------------------------

  procedure Wait_For_Incoming_Events
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : out vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    process_package_vt_crazyflie_start_demo_Interrogators.Wait_For_Incoming_Events
     (Port);
  end Wait_For_Incoming_Events;

  ----------------------------
  -- Store_Received_Message -- 
  ----------------------------

  procedure Store_Received_Message
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Interface;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Time_Stamp : Ada.Real_Time.Time :=
      Ada.Real_Time.Clock)
  is
    use PolyORB_HI_Generated.Deployment;
    pragma Unreferenced
     (Entity);
  begin
    process_package_vt_crazyflie_start_demo_Interrogators.Store_Received_Message
     (Thread_Interface,
      From,
      Time_Stamp);
  end Store_Received_Message;

  -------------------------------------------------
  -- process_package_vt_crazyflie_start_demo_Job -- 
  -------------------------------------------------

  procedure process_package_vt_crazyflie_start_demo_Job
   (Port : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type;
    Result : out PolyORB_HI.Errors.Error_Kind)
  is
    INPORT_artificial_start_demo_V : PolyORB_HI_Generated.Types.T_Uint16_Buffer_impl;
    INPORT_artificial_start_demo_C : constant Standard.Integer :=
     process_package_vt_crazyflie_start_demo_Interrogators.Get_Count
       (INPORT_artificial_start_demo);
    pragma Unreferenced
     (Port);
    Error_Ü : constant PolyORB_HI.Errors.Error_Kind :=
     PolyORB_HI.Errors.Error_None;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Depending on the triggered port, call the corresponding compute 
    --  entrypoint.
    if (INPORT_artificial_start_demo_C
      /= -1)
    then
      INPORT_artificial_start_demo_V :=
       process_package_vt_crazyflie_start_demo_Interrogators.Get_Value
         (INPORT_artificial_start_demo).INPORT_artificial_start_demo_DATA;
    else
      INPORT_artificial_start_demo_V :=
       PolyORB_HI_Generated.Types.T_Uint16_Buffer_impl_Default_Value;
    end if;
    --  Dequeue the IN port values
    process_package_vt_crazyflie_start_demo_Interrogators.Next_Value
     (vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Port_Type'
       (INPORT_artificial_start_demo));
    vt_crazyflie_start_demo_wrappers.artificial_start_demo
     (PolyORB_HI_Generated.Deployment.crazyflie_v2_partition_vt_crazyflie_start_demo_K,
      INPORT_artificial_start_demo_V);
    --  Return error code
    Result :=
     Error_Ü;
  end process_package_vt_crazyflie_start_demo_Job;

  --------------------------------
  -- Crazyflie_BLE_receiver_Job -- 
  --------------------------------

  procedure Crazyflie_BLE_receiver_Job
   (Result : out PolyORB_HI.Errors.Error_Kind)
  is
    Error_Ü : constant PolyORB_HI.Errors.Error_Kind :=
     PolyORB_HI.Errors.Error_None;
    use type PolyORB_HI.Errors.Error_Kind;
  begin
    --  Call implementation
    PolyORB_HI_Generated.Subprograms.Crazyflie_BLE_Receive;
    --  Return error code
    Result :=
     Error_Ü;
  end Crazyflie_BLE_receiver_Job;

end PolyORB_HI_Generated.Activity;
