--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with Interfaces;
with PolyORB_HI.Port_Type_Marshallers;
with PolyORB_HI.Port_Types;
with PolyORB_HI_Generated.Activity;
use PolyORB_HI_Generated.Activity;
with PolyORB_HI_Generated.Marshallers;

package body PolyORB_HI_Generated.Transport is

  procedure process_package_vt_crazyflie_start_demo_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type);

  -------------
  -- Deliver -- 
  -------------

  procedure Deliver
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Streams.Stream_Element_Array)
  is
    use PolyORB_HI_Generated.Deployment;
    Msg : PolyORB_HI.Messages.Message_Type;
    Value : Interfaces.Unsigned_16;
    Port : PolyORB_HI_Generated.Deployment.Port_Type;
    use type PolyORB_HI.Streams.Stream_Element_Offset;
  begin
    PolyORB_HI.Messages.Write
     (Msg,
      Message
       ((Message'First
          + PolyORB_HI.Messages.Header_Size) .. Message'Last));
    PolyORB_HI.Port_Type_Marshallers.Unmarshall
     (Value,
      Msg);
    Port :=
     PolyORB_HI.Port_Types.Corresponding_Port
       (Value);
    if (Entity
      = PolyORB_HI_Generated.Deployment.crazyflie_v2_partition_vt_crazyflie_start_demo_K)
    then
      process_package_vt_crazyflie_start_demo_Deliver
       (Port,
        PolyORB_HI.Messages.Sender
         (Message),
        Msg);
    end if;
  end Deliver;

  ----------
  -- Send -- 
  ----------

  function Send
   (From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Message : PolyORB_HI.Messages.Message_Type)
   return PolyORB_HI.Errors.Error_Kind
  is
    pragma Unreferenced
     (From,
      Entity,
      Message);
  begin
    return PolyORB_HI.Errors.Error_Kind'
     (PolyORB_HI.Errors.Error_Transport);
  end Send;

  -----------------------------------------------------
  -- process_package_vt_crazyflie_start_demo_Deliver -- 
  -----------------------------------------------------

  procedure process_package_vt_crazyflie_start_demo_Deliver
   (Port : PolyORB_HI_Generated.Deployment.Port_Type;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Msg : in out PolyORB_HI.Messages.Message_Type)
  is
    use PolyORB_HI_Generated.Deployment;
    Thread_Interface_Ü : vt_crazyflie_start_demo_CV_Thread_vt_crazyflie_start_demo_vt_crazyflie_start_demo_others_Interface;
  begin
    if (Port
      = PolyORB_HI_Generated.Deployment.crazyflie_v2_partition_vt_crazyflie_start_demo_INPORT_artificial_start_demo_K)
    then
      PolyORB_HI_Generated.Marshallers.Unmarshall
       (INPORT_artificial_start_demo,
        Thread_Interface_Ü,
        Msg);
      PolyORB_HI_Generated.Activity.Store_Received_Message
       (PolyORB_HI_Generated.Deployment.crazyflie_v2_partition_vt_crazyflie_start_demo_K,
        Thread_Interface_Ü,
        From);
    end if;
  end process_package_vt_crazyflie_start_demo_Deliver;

end PolyORB_HI_Generated.Transport;
